#!/usr/bin/env bash
set -euo pipefail

echo "============================================"
echo "  AI HQ — Autonomous Operations Centre"
echo "  One-Click Setup Script"
echo "============================================"
echo ""

# Color helpers
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
fail() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ── Check Python 3.10+ ──
echo "Checking dependencies..."
if command -v python3 &>/dev/null; then
  PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
  PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
  PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)
  if [ "$PY_MAJOR" -ge 3 ] && [ "$PY_MINOR" -ge 10 ]; then
    ok "Python $PY_VERSION detected"
  else
    fail "Python 3.10+ required (found $PY_VERSION). Please upgrade."
  fi
else
  fail "Python 3 not found. Install Python 3.10+ from https://python.org"
fi

# ── Check Node.js ──
if command -v node &>/dev/null; then
  NODE_VERSION=$(node --version)
  ok "Node.js $NODE_VERSION detected"
else
  warn "Node.js not found. Some features may not work. Install from https://nodejs.org"
fi

# ── Create virtual environment ──
echo ""
echo "Setting up Python virtual environment..."
if [ ! -d "venv" ]; then
  python3 -m venv venv
  ok "Virtual environment created at ./venv"
else
  ok "Virtual environment already exists"
fi

source venv/bin/activate
ok "Activated virtual environment"

# ── Install Python dependencies ──
echo ""
echo "Installing Python dependencies..."
if [ -f "requirements.txt" ]; then
  pip install --upgrade pip -q
  pip install -r requirements.txt -q
  ok "Python dependencies installed"
else
  warn "No requirements.txt found — skipping pip install"
fi

# ── API Key Configuration ──
echo ""
echo "============================================"
echo "  API Key Configuration"
echo "============================================"
echo ""
echo "We'll now configure your environment variables."
echo "Press Enter to skip any key you don't have yet."
echo ""

ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  warn "Existing .env file found. We'll update only empty values."
  source "$ENV_FILE" 2>/dev/null || true
fi

prompt_key() {
  local VAR_NAME="$1"
  local DESCRIPTION="$2"
  local CURRENT="${!VAR_NAME:-}"

  if [ -n "$CURRENT" ] && [ "$CURRENT" != "" ]; then
    ok "$VAR_NAME already set"
    return
  fi

  read -rp "  $DESCRIPTION [$VAR_NAME]: " VALUE
  if [ -n "$VALUE" ]; then
    echo "${VAR_NAME}=${VALUE}" >> "$ENV_FILE"
    ok "$VAR_NAME saved"
  else
    warn "$VAR_NAME skipped (you can add it to .env later)"
  fi
}

# Only create .env if it doesn't exist
if [ ! -f "$ENV_FILE" ]; then
  touch "$ENV_FILE"
  echo "# AI HQ Environment Variables" >> "$ENV_FILE"
  echo "# Generated by install.sh on $(date)" >> "$ENV_FILE"
  echo "" >> "$ENV_FILE"
fi

prompt_key "ANTHROPIC_API_KEY"     "Anthropic API key (sk-ant-...)"
prompt_key "STRIPE_SECRET_KEY"     "Stripe Secret key (sk_live_... or sk_test_...)"
prompt_key "STRIPE_PUBLISHABLE_KEY" "Stripe Publishable key (pk_live_... or pk_test_...)"
prompt_key "TELEGRAM_BOT_TOKEN"    "Telegram Bot token"
prompt_key "TELEGRAM_CHAT_ID"      "Telegram Chat ID"
prompt_key "BLUESKY_HANDLE"        "Bluesky handle (user.bsky.social)"
prompt_key "BLUESKY_APP_PASSWORD"  "Bluesky app password"
prompt_key "NGROK_AUTH_TOKEN"      "Ngrok auth token (optional)"

echo ""
ok "Environment configured. Edit .env to change values anytime."

# ── Start the server ──
echo ""
echo "============================================"
echo "  Starting AI HQ Server"
echo "============================================"
echo ""

if [ -f "agent_server.py" ]; then
  echo "Launching agent_server.py on port 5050..."
  python3 agent_server.py &
  SERVER_PID=$!
  sleep 2

  if kill -0 "$SERVER_PID" 2>/dev/null; then
    ok "AI HQ server running (PID: $SERVER_PID)"
    echo ""
    echo "============================================"
    echo "  AI HQ is live!"
    echo "  Dashboard: http://localhost:5050"
    echo "  API:       http://localhost:5050/api/status"
    echo "============================================"
  else
    fail "Server failed to start. Check server.log for details."
  fi
else
  warn "agent_server.py not found. Please ensure the server file exists."
fi
